const http = require('http');
const WebSocket = require('ws');
const axios = require('axios');

const server = http.createServer((req, res) => {
  res.writeHead(200);
    res.end('Bridge is running');
    });
    server.listen(process.env.PORT || 3000);

    const API_KEY = process.env.FINNHUB_API_KEY;
    const N8N_WEBHOOK_URL = process.env.N8N_WEBHOOK_URL;

    // Finnhub uses different symbol formats per asset class
    const STOCK_SYMBOLS  = ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'AMZN'];
    const FOREX_SYMBOLS  = ['OANDA:EUR_USD', 'OANDA:GBP_USD', 'OANDA:USD_JPY', 'OANDA:AUD_USD', 'OANDA:USD_CHF'];
    const CRYPTO_SYMBOLS = ['BINANCE:BTCUSDT', 'BINANCE:ETHUSDT', 'BINANCE:SOLUSDT', 'BINANCE:BNBUSDT', 'BINANCE:XRPUSDT'];

    const ALL_SYMBOLS = [...STOCK_SYMBOLS, ...FOREX_SYMBOLS, ...CRYPTO_SYMBOLS];

    // Normalize Finnhub symbol to a clean name for your payload
    function cleanSymbol(sym) {
      return sym
          .replace('OANDA:', '').replace('_', '-')
              .replace('BINANCE:', '').replace('USDT', '-USD');
              }

              function detectFeed(sym) {
                if (STOCK_SYMBOLS.includes(sym)) return 'stocks';
                  if (FOREX_SYMBOLS.includes(sym)) return 'forex';
                    return 'crypto';
                    }

                    // Per-symbol price history
                    const history = {};

                    function getHistory(symbol) {
                      if (!history[symbol]) history[symbol] = { prices: [] };
                        return history[symbol];
                        }

                        function updateHistory(symbol, price) {
                          const h = getHistory(symbol);
                            h.prices.push(price);
                              if (h.prices.length > 100) h.prices.shift();
                              }

                              function mean(arr) {
                                return arr.reduce((a, b) => a + b, 0) / arr.length;
                                }

                                function median(arr) {
                                  const s = [...arr].sort((a, b) => a - b);
                                    const m = Math.floor(s.length / 2);
                                      return s.length % 2 !== 0 ? s[m] : (s[m - 1] + s[m]) / 2;
                                      }

                                      function variance(arr, avg) {
                                        return arr.reduce((s, v) => s + Math.pow(v - avg, 2), 0) / arr.length;
                                        }

                                        function stdDev(arr) {
                                          return Math.sqrt(variance(arr, mean(arr)));
                                          }

                                          function skewness(arr) {
                                            const m = mean(arr), s = stdDev(arr);
                                              if (s === 0) return 0;
                                                return arr.reduce((sum, v) => sum + Math.pow((v - m) / s, 3), 0) / arr.length;
                                                }

                                                function kurtosis(arr) {
                                                  const m = mean(arr), s = stdDev(arr);
                                                    if (s === 0) return 0;
                                                      return arr.reduce((sum, v) => sum + Math.pow((v - m) / s, 4), 0) / arr.length;
                                                      }

                                                      function zscores(arr) {
                                                        const m = mean(arr), s = stdDev(arr);
                                                          if (s === 0) return arr.map(() => 0);
                                                            return arr.map(v => parseFloat(((v - m) / s).toFixed(4)));
                                                            }

                                                            function returns(prices) {
                                                              const r = [];
                                                                for (let i = 1; i < prices.length; i++) {
                                                                    r.push(parseFloat(((prices[i] - prices[i - 1]) / prices[i - 1]).toFixed(6)));
                                                                      }
                                                                        return r;
                                                                        }

                                                                        function maxDrawdown(prices) {
                                                                          let maxDD = 0, peak = prices[0];
                                                                            for (const p of prices) {
                                                                                if (p > peak) peak = p;
                                                                                    const dd = peak - p;
                                                                                        if (dd > maxDD) maxDD = dd;
                                                                                          }
                                                                                            return parseFloat(maxDD.toFixed(6));
                                                                                            }

                                                                                            function velocity(prices) {
                                                                                              const v = [];
                                                                                                for (let i = 1; i < prices.length; i++) {
                                                                                                    v.push(parseFloat((prices[i] - prices[i - 1]).toFixed(6)));
                                                                                                      }
                                                                                                        return v.slice(-6);
                                                                                                        }

                                                                                                        function acceleration(vel) {
                                                                                                          const a = [];
                                                                                                            for (let i = 1; i < vel.length; i++) {
                                                                                                                a.push(parseFloat((vel[i] - vel[i - 1]).toFixed(6)));
                                                                                                                  }
                                                                                                                    return a.slice(-5);
                                                                                                                    }

                                                                                                                    function sequence(prices) {
                                                                                                                      return prices.slice(-9).map((p, i, arr) => {
                                                                                                                          if (i === 0) return 1;
                                                                                                                              return p >= arr[i - 1] ? 1 : -1;
                                                                                                                                });
                                                                                                                                }

                                                                                                                                function countSwings(seq) {
                                                                                                                                  let swings = 0;
                                                                                                                                    for (let i = 1; i < seq.length; i++) {
                                                                                                                                        if (seq[i] !== seq[i - 1]) swings++;
                                                                                                                                          }
                                                                                                                                            return swings;
                                                                                                                                            }

                                                                                                                                            function entropy(prices) {
                                                                                                                                              const r = returns(prices);
                                                                                                                                                if (r.length === 0) return 0;
                                                                                                                                                  const pos = r.filter(x => x > 0).length / r.length;
                                                                                                                                                    const neg = 1 - pos;
                                                                                                                                                      if (pos === 0 || neg === 0) return 0;
                                                                                                                                                        return parseFloat((-pos * Math.log2(pos) - neg * Math.log2(neg)).toFixed(4));
                                                                                                                                                        }

                                                                                                                                                        function normalize(arr) {
                                                                                                                                                          const min = Math.min(...arr), max = Math.max(...arr);
                                                                                                                                                            const range = max - min;
                                                                                                                                                              if (range === 0) return arr.map(() => 0.5);
                                                                                                                                                                return arr.slice(-9).map(v => parseFloat(((v - min) / range).toFixed(2)));
                                                                                                                                                                }

                                                                                                                                                                function volatilitySurface(prices) {
                                                                                                                                                                  return [5, 10, 20, 30, 50].map(w => {
                                                                                                                                                                      const slice = prices.slice(-w);
                                                                                                                                                                          if (slice.length < 2) return 0;
                                                                                                                                                                              return parseFloat(stdDev(slice).toFixed(6));
                                                                                                                                                                                });
                                                                                                                                                                                }

                                                                                                                                                                                function supportResistance(prices) {
                                                                                                                                                                                  return {
                                                                                                                                                                                      support: parseFloat(Math.min(...prices.slice(-50)).toFixed(5)),
                                                                                                                                                                                          resistance: parseFloat(Math.max(...prices.slice(-50)).toFixed(5)),
                                                                                                                                                                                            };
                                                                                                                                                                                            }

                                                                                                                                                                                            function multiTimeframe(prices) {
                                                                                                                                                                                              const sa = parseFloat(mean(prices.slice(-5)).toFixed(5));
                                                                                                                                                                                                const ma = parseFloat(mean(prices.slice(-20)).toFixed(5));
                                                                                                                                                                                                  const la = parseFloat(mean(prices.slice(-50)).toFixed(5));
                                                                                                                                                                                                    return {
                                                                                                                                                                                                        short_avg: sa, medium_avg: ma, long_avg: la,
                                                                                                                                                                                                            short_vs_long: parseFloat((sa - la).toFixed(6)),
                                                                                                                                                                                                                medium_vs_long: parseFloat((ma - la).toFixed(6)),
                                                                                                                                                                                                                  };
                                                                                                                                                                                                                  }

                                                                                                                                                                                                                  function buildPayload(symbol, price, feed) {
                                                                                                                                                                                                                    updateHistory(symbol, price);
                                                                                                                                                                                                                      const prices = getHistory(symbol).prices;
                                                                                                                                                                                                                        if (prices.length < 5) return null;

                                                                                                                                                                                                                          const avg  = parseFloat(mean(prices).toFixed(5));
                                                                                                                                                                                                                            const med  = parseFloat(median(prices).toFixed(5));
                                                                                                                                                                                                                              const maxP = parseFloat(Math.max(...prices).toFixed(5));
                                                                                                                                                                                                                                const minP = parseFloat(Math.min(...prices).toFixed(5));
                                                                                                                                                                                                                                  const vel  = velocity(prices);
                                                                                                                                                                                                                                    const accel = acceleration(vel);
                                                                                                                                                                                                                                      const seq  = sequence(prices);
                                                                                                                                                                                                                                        const rets = returns(prices).slice(-8);
                                                                                                                                                                                                                                          const zs   = zscores(prices.slice(-5));
                                                                                                                                                                                                                                            const vari = parseFloat(variance(prices, avg).toFixed(10));
                                                                                                                                                                                                                                              const std  = parseFloat(stdDev(prices).toFixed(6));
                                                                                                                                                                                                                                                const skew = parseFloat(skewness(prices).toFixed(4));
                                                                                                                                                                                                                                                  const kurt = parseFloat(kurtosis(prices).toFixed(4));
                                                                                                                                                                                                                                                    const buyPressure  = parseFloat((price * 0.0001).toFixed(6));
                                                                                                                                                                                                                                                      const sellPressure = parseFloat((price * 0.00009).toFixed(6));
                                                                                                                                                                                                                                                        const efficiency   = parseFloat((1 - 0.0001 / (maxP - minP || 0.0001)).toFixed(4));
                                                                                                                                                                                                                                                          const imbalance    = 1;
                                                                                                                                                                                                                                                            const cumMomentum  = parseFloat(rets.reduce((a, b) => a + b, 0).toFixed(6));
                                                                                                                                                                                                                                                              const momStrength  = parseFloat(Math.abs(cumMomentum).toFixed(6));
                                                                                                                                                                                                                                                                const swings = countSwings(seq);
                                                                                                                                                                                                                                                                  const norm   = normalize(prices);
                                                                                                                                                                                                                                                                    const ent    = entropy(prices);
                                                                                                                                                                                                                                                                      const avgSpeed = parseFloat(mean(vel.map(Math.abs)).toFixed(6));
                                                                                                                                                                                                                                                                        const avgAccel = accel.length > 0 ? parseFloat(mean(accel.map(Math.abs)).toFixed(6)) : 0;

                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                              symbol, feed,
                                                                                                                                                                                                                                                                                  raw: { price },
                                                                                                                                                                                                                                                                                      price: {
                                                                                                                                                                                                                                                                                            avg, median: med,
                                                                                                                                                                                                                                                                                                  mid: parseFloat(((maxP + minP) / 2).toFixed(5)),
                                                                                                                                                                                                                                                                                                        max: maxP, min: minP,
                                                                                                                                                                                                                                                                                                              range: parseFloat((maxP - minP).toFixed(6)),
                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                      stats: { variance: vari, std, skewness: skew, kurtosis: kurt, zscores: zs },
                                                                                                                                                                                                                                                                                                                          microstructure: { imbalance, buyPressure, sellPressure, efficiency },
                                                                                                                                                                                                                                                                                                                              time: { velocity: vel, acceleration: accel, avgSpeed, avgAccel },
                                                                                                                                                                                                                                                                                                                                  structure: { sequence: seq, swings, cycles: Math.floor(swings / 2) },
                                                                                                                                                                                                                                                                                                                                      history: {
                                                                                                                                                                                                                                                                                                                                            high: maxP, low: minP,
                                                                                                                                                                                                                                                                                                                                                  range: parseFloat((maxP - minP).toFixed(6)),
                                                                                                                                                                                                                                                                                                                                                        returns: rets,
                                                                                                                                                                                                                                                                                                                                                              max_drawdown: maxDrawdown(prices),
                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                      momentum: { raw: rets.slice(-4), cumulative: cumMomentum, strength: momStrength },
                                                                                                                                                                                                                                                                                                                                                                          volatility_surface: volatilitySurface(prices),
                                                                                                                                                                                                                                                                                                                                                                              support_resistance: supportResistance(prices),
                                                                                                                                                                                                                                                                                                                                                                                  patterns: seq.slice(-5),
                                                                                                                                                                                                                                                                                                                                                                                      behavior: {
                                                                                                                                                                                                                                                                                                                                                                                            aggression: parseFloat((buyPressure + sellPressure).toFixed(6)),
                                                                                                                                                                                                                                                                                                                                                                                                  stability: parseFloat((1 - std / (avg || 1)).toFixed(4)),
                                                                                                                                                                                                                                                                                                                                                                                                        expansion: parseFloat((maxP - minP).toFixed(6)),
                                                                                                                                                                                                                                                                                                                                                                                                              compression: parseFloat((std / (maxP - minP || 0.0001)).toFixed(4)),
                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                      multi_timeframe: multiTimeframe(prices),
                                                                                                                                                                                                                                                                                                                                                                                                                          normalized_series: norm,
                                                                                                                                                                                                                                                                                                                                                                                                                              entropy: ent,
                                                                                                                                                                                                                                                                                                                                                                                                                                  ai_matrix: prices.slice(-4).map((p, i) => [
                                                                                                                                                                                                                                                                                                                                                                                                                                        parseFloat(p.toFixed(4)),
                                                                                                                                                                                                                                                                                                                                                                                                                                              vel[i] || 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    accel[i] || 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          norm[i] || 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ai_vector: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        avg, parseFloat((maxP - minP).toFixed(6)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              std, skew, kurt,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    buyPressure, sellPressure,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          avgSpeed, avgAccel,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                swings, cumMomentum, ent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      let reconnectDelay = 3000;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function connect() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const ws = new WebSocket(`wss://ws.finnhub.io?token=${API_KEY}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ws.on('open', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('[Finnhub] Connected');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  reconnectDelay = 3000;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ALL_SYMBOLS.forEach(sym => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ws.send(JSON.stringify({ type: 'subscribe', symbol: sym }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`[Finnhub] Subscribed to ${ALL_SYMBOLS.length} symbols`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ws.on('message', async (raw) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const msg = JSON.parse(raw);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (msg.type !== 'trade' || !msg.data) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (const tick of msg.data) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const rawSym = tick.s;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const price  = parseFloat(tick.p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!price) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const symbol = cleanSymbol(rawSym);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const feed   = detectFeed(rawSym);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const payload = buildPayload(symbol, price, feed);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!payload) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await axios.post(N8N_WEBHOOK_URL, payload, { timeout: 5000 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`[${feed}] Sent ${symbol} @ ${price}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error(`[${feed}] Failed to send:`, err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ws.on('close', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`[Finnhub] Disconnected. Reconnecting in ${reconnectDelay}ms`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(connect, reconnectDelay);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            reconnectDelay = Math.min(reconnectDelay * 2, 30000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ws.on('error', (err) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('[Finnhub] Error:', err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ws.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          connect();