const http = require('http');
const WebSocket = require('ws');
const axios = require('axios');

const server = http.createServer((req, res) => {
  res.writeHead(200);
    res.end('Bridge is running');
    });
    server.listen(process.env.PORT || 3000);

    const API_KEY = process.env.MASSIVE_API_KEY;
    const N8N_WEBHOOK_URL = process.env.N8N_WEBHOOK_URL;

    // Your selected symbols
    const SYMBOLS_FILTER = [
      // Forex
        'USD-JPY', 'EUR-USD', 'GBP-USD', 'AUD-USD', 'USD-CHF',
          // Crypto
            'BTC-USD', 'ETH-USD', 'SOL-USD', 'BNB-USD', 'XRP-USD',
              // Stocks
                'AAPL', 'TSLA', 'MSFT', 'NVDA', 'AMZN',
                ];

                // Per-symbol price history store
                const history = {};

                function getHistory(symbol) {
                  if (!history[symbol]) {
                      history[symbol] = { prices: [] };
                        }
                          return history[symbol];
                          }

                          function updateHistory(symbol, price) {
                            const h = getHistory(symbol);
                              h.prices.push(price);
                                if (h.prices.length > 100) h.prices.shift();
                                }

                                function mean(arr) {
                                  return arr.reduce((a, b) => a + b, 0) / arr.length;
                                  }

                                  function median(arr) {
                                    const s = [...arr].sort((a, b) => a - b);
                                      const m = Math.floor(s.length / 2);
                                        return s.length % 2 !== 0 ? s[m] : (s[m - 1] + s[m]) / 2;
                                        }

                                        function variance(arr, avg) {
                                          return arr.reduce((s, v) => s + Math.pow(v - avg, 2), 0) / arr.length;
                                          }

                                          function stdDev(arr) {
                                            return Math.sqrt(variance(arr, mean(arr)));
                                            }

                                            function skewness(arr) {
                                              const m = mean(arr);
                                                const s = stdDev(arr);
                                                  if (s === 0) return 0;
                                                    return arr.reduce((sum, v) => sum + Math.pow((v - m) / s, 3), 0) / arr.length;
                                                    }

                                                    function kurtosis(arr) {
                                                      const m = mean(arr);
                                                        const s = stdDev(arr);
                                                          if (s === 0) return 0;
                                                            return arr.reduce((sum, v) => sum + Math.pow((v - m) / s, 4), 0) / arr.length;
                                                            }

                                                            function zscores(arr) {
                                                              const m = mean(arr);
                                                                const s = stdDev(arr);
                                                                  if (s === 0) return arr.map(() => 0);
                                                                    return arr.map(v => parseFloat(((v - m) / s).toFixed(4)));
                                                                    }

                                                                    function returns(prices) {
                                                                      const r = [];
                                                                        for (let i = 1; i < prices.length; i++) {
                                                                            r.push(parseFloat(((prices[i] - prices[i - 1]) / prices[i - 1]).toFixed(6)));
                                                                              }
                                                                                return r;
                                                                                }

                                                                                function maxDrawdown(prices) {
                                                                                  let maxDD = 0;
                                                                                    let peak = prices[0];
                                                                                      for (const p of prices) {
                                                                                          if (p > peak) peak = p;
                                                                                              const dd = peak - p;
                                                                                                  if (dd > maxDD) maxDD = dd;
                                                                                                    }
                                                                                                      return parseFloat(maxDD.toFixed(6));
                                                                                                      }

                                                                                                      function velocity(prices) {
                                                                                                        const v = [];
                                                                                                          for (let i = 1; i < prices.length; i++) {
                                                                                                              v.push(parseFloat((prices[i] - prices[i - 1]).toFixed(6)));
                                                                                                                }
                                                                                                                  return v.slice(-6);
                                                                                                                  }

                                                                                                                  function acceleration(vel) {
                                                                                                                    const a = [];
                                                                                                                      for (let i = 1; i < vel.length; i++) {
                                                                                                                          a.push(parseFloat((vel[i] - vel[i - 1]).toFixed(6)));
                                                                                                                            }
                                                                                                                              return a.slice(-5);
                                                                                                                              }

                                                                                                                              function sequence(prices) {
                                                                                                                                return prices.slice(-9).map((p, i, arr) => {
                                                                                                                                    if (i === 0) return 1;
                                                                                                                                        return p >= arr[i - 1] ? 1 : -1;
                                                                                                                                          });
                                                                                                                                          }

                                                                                                                                          function countSwings(seq) {
                                                                                                                                            let swings = 0;
                                                                                                                                              for (let i = 1; i < seq.length; i++) {
                                                                                                                                                  if (seq[i] !== seq[i - 1]) swings++;
                                                                                                                                                    }
                                                                                                                                                      return swings;
                                                                                                                                                      }

                                                                                                                                                      function entropy(prices) {
                                                                                                                                                        const r = returns(prices);
                                                                                                                                                          if (r.length === 0) return 0;
                                                                                                                                                            const pos = r.filter(x => x > 0).length / r.length;
                                                                                                                                                              const neg = 1 - pos;
                                                                                                                                                                if (pos === 0 || neg === 0) return 0;
                                                                                                                                                                  return parseFloat((-pos * Math.log2(pos) - neg * Math.log2(neg)).toFixed(4));
                                                                                                                                                                  }

                                                                                                                                                                  function normalize(arr) {
                                                                                                                                                                    const min = Math.min(...arr);
                                                                                                                                                                      const max = Math.max(...arr);
                                                                                                                                                                        const range = max - min;
                                                                                                                                                                          if (range === 0) return arr.map(() => 0.5);
                                                                                                                                                                            return arr.slice(-9).map(v => parseFloat(((v - min) / range).toFixed(2)));
                                                                                                                                                                            }

                                                                                                                                                                            function volatilitySurface(prices) {
                                                                                                                                                                              return [5, 10, 20, 30, 50].map(w => {
                                                                                                                                                                                  const slice = prices.slice(-w);
                                                                                                                                                                                      if (slice.length < 2) return 0;
                                                                                                                                                                                          return parseFloat(stdDev(slice).toFixed(6));
                                                                                                                                                                                            });
                                                                                                                                                                                            }

                                                                                                                                                                                            function supportResistance(prices) {
                                                                                                                                                                                              return {
                                                                                                                                                                                                  support: parseFloat(Math.min(...prices.slice(-50)).toFixed(5)),
                                                                                                                                                                                                      resistance: parseFloat(Math.max(...prices.slice(-50)).toFixed(5)),
                                                                                                                                                                                                        };
                                                                                                                                                                                                        }

                                                                                                                                                                                                        function multiTimeframe(prices) {
                                                                                                                                                                                                          const sa = parseFloat(mean(prices.slice(-5)).toFixed(5));
                                                                                                                                                                                                            const ma = parseFloat(mean(prices.slice(-20)).toFixed(5));
                                                                                                                                                                                                              const la = parseFloat(mean(prices.slice(-50)).toFixed(5));
                                                                                                                                                                                                                return {
                                                                                                                                                                                                                    short_avg: sa,
                                                                                                                                                                                                                        medium_avg: ma,
                                                                                                                                                                                                                            long_avg: la,
                                                                                                                                                                                                                                short_vs_long: parseFloat((sa - la).toFixed(6)),
                                                                                                                                                                                                                                    medium_vs_long: parseFloat((ma - la).toFixed(6)),
                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                      function buildPayload(symbol, price, bid, ask, feed) {
                                                                                                                                                                                                                                        updateHistory(symbol, price);
                                                                                                                                                                                                                                          const prices = getHistory(symbol).prices;
                                                                                                                                                                                                                                            if (prices.length < 5) return null;

                                                                                                                                                                                                                                              const avg = parseFloat(mean(prices).toFixed(5));
                                                                                                                                                                                                                                                const med = parseFloat(median(prices).toFixed(5));
                                                                                                                                                                                                                                                  const maxP = parseFloat(Math.max(...prices).toFixed(5));
                                                                                                                                                                                                                                                    const minP = parseFloat(Math.min(...prices).toFixed(5));
                                                                                                                                                                                                                                                      const vel = velocity(prices);
                                                                                                                                                                                                                                                        const accel = acceleration(vel);
                                                                                                                                                                                                                                                          const seq = sequence(prices);
                                                                                                                                                                                                                                                            const rets = returns(prices).slice(-8);
                                                                                                                                                                                                                                                              const zs = zscores(prices.slice(-5));
                                                                                                                                                                                                                                                                const vari = parseFloat(variance(prices, avg).toFixed(10));
                                                                                                                                                                                                                                                                  const std = parseFloat(stdDev(prices).toFixed(6));
                                                                                                                                                                                                                                                                    const skew = parseFloat(skewness(prices).toFixed(4));
                                                                                                                                                                                                                                                                      const kurt = parseFloat(kurtosis(prices).toFixed(4));
                                                                                                                                                                                                                                                                        const buyPressure = parseFloat(Math.abs(price - (bid || price - 0.0001)).toFixed(6));
                                                                                                                                                                                                                                                                          const sellPressure = parseFloat(Math.abs((ask || price + 0.0001) - price).toFixed(6));
                                                                                                                                                                                                                                                                            const spread = ask && bid ? ask - bid : 0.0001;
                                                                                                                                                                                                                                                                              const efficiency = parseFloat((1 - spread / (maxP - minP || 0.0001)).toFixed(4));
                                                                                                                                                                                                                                                                                const imbalance = buyPressure > sellPressure ? 1 : -1;
                                                                                                                                                                                                                                                                                  const cumMomentum = parseFloat(rets.reduce((a, b) => a + b, 0).toFixed(6));
                                                                                                                                                                                                                                                                                    const momStrength = parseFloat(Math.abs(cumMomentum).toFixed(6));
                                                                                                                                                                                                                                                                                      const swings = countSwings(seq);
                                                                                                                                                                                                                                                                                        const norm = normalize(prices);
                                                                                                                                                                                                                                                                                          const ent = entropy(prices);
                                                                                                                                                                                                                                                                                            const avgSpeed = parseFloat(mean(vel.map(Math.abs)).toFixed(6));
                                                                                                                                                                                                                                                                                              const avgAccel = parseFloat(mean(accel.map(Math.abs)).toFixed(6));

                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                    symbol,
                                                                                                                                                                                                                                                                                                        feed,
                                                                                                                                                                                                                                                                                                            raw: { price, bid: bid || null, ask: ask || null },
                                                                                                                                                                                                                                                                                                                price: {
                                                                                                                                                                                                                                                                                                                      avg, median: med,
                                                                                                                                                                                                                                                                                                                            mid: parseFloat(((maxP + minP) / 2).toFixed(5)),
                                                                                                                                                                                                                                                                                                                                  max: maxP, min: minP,
                                                                                                                                                                                                                                                                                                                                        range: parseFloat((maxP - minP).toFixed(6)),
                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                stats: { variance: vari, std, skewness: skew, kurtosis: kurt, zscores: zs },
                                                                                                                                                                                                                                                                                                                                                    microstructure: { imbalance, buyPressure, sellPressure, efficiency },
                                                                                                                                                                                                                                                                                                                                                        time: { velocity: vel, acceleration: accel, avgSpeed, avgAccel },
                                                                                                                                                                                                                                                                                                                                                            structure: { sequence: seq, swings, cycles: Math.floor(swings / 2) },
                                                                                                                                                                                                                                                                                                                                                                history: { high: maxP, low: minP, range: parseFloat((maxP - minP).toFixed(6)), returns: rets, max_drawdown: maxDrawdown(prices) },
                                                                                                                                                                                                                                                                                                                                                                    momentum: { raw: rets.slice(-4), cumulative: cumMomentum, strength: momStrength },
                                                                                                                                                                                                                                                                                                                                                                        volatility_surface: volatilitySurface(prices),
                                                                                                                                                                                                                                                                                                                                                                            support_resistance: supportResistance(prices),
                                                                                                                                                                                                                                                                                                                                                                                patterns: seq.slice(-5),
                                                                                                                                                                                                                                                                                                                                                                                    behavior: {
                                                                                                                                                                                                                                                                                                                                                                                          aggression: parseFloat((buyPressure + sellPressure).toFixed(6)),
                                                                                                                                                                                                                                                                                                                                                                                                stability: parseFloat((1 - std / (avg || 1)).toFixed(4)),
                                                                                                                                                                                                                                                                                                                                                                                                      expansion: parseFloat((maxP - minP).toFixed(6)),
                                                                                                                                                                                                                                                                                                                                                                                                            compression: parseFloat((std / (maxP - minP || 0.0001)).toFixed(4)),
                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                    multi_timeframe: multiTimeframe(prices),
                                                                                                                                                                                                                                                                                                                                                                                                                        normalized_series: norm,
                                                                                                                                                                                                                                                                                                                                                                                                                            entropy: ent,
                                                                                                                                                                                                                                                                                                                                                                                                                                ai_matrix: prices.slice(-4).map((p, i) => [
                                                                                                                                                                                                                                                                                                                                                                                                                                      parseFloat(p.toFixed(4)),
                                                                                                                                                                                                                                                                                                                                                                                                                                            vel[i] || 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  accel[i] || 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        norm[i] || 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ai_vector: [avg, parseFloat((maxP - minP).toFixed(6)), std, skew, kurt, buyPressure, sellPressure, avgSpeed, avgAccel, swings, cumMomentum, ent],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const FEEDS = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { name: 'stocks', url: 'wss://socket.massive.com/stocks', subscribe: 'T.AAPL,T.TSLA,T.MSFT,T.NVDA,T.AMZN' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { name: 'forex', url: 'wss://socket.massive.com/forex', subscribe: 'C.USD-JPY,C.EUR-USD,C.GBP-USD,C.AUD-USD,C.USD-CHF' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { name: 'crypto', url: 'wss://socket.massive.com/crypto', subscribe: 'XT.BTC-USD,XT.ETH-USD,XT.SOL-USD,XT.BNB-USD,XT.XRP-USD' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function connectFeed(feed, reconnectDelay = 3000) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const ws = new WebSocket(feed.url);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ws.on('open', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`[${feed.name}] Connected`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ws.send(JSON.stringify({ action: 'auth', params: API_KEY }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ws.on('message', async (raw) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const messages = JSON.parse(raw);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (const msg of messages) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (msg.status === 'auth_success') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ws.send(JSON.stringify({ action: 'subscribe', params: feed.subscribe }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`[${feed.name}] Subscribed to selected symbols`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (msg.ev && msg.ev !== 'status') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const symbol = msg.sym || msg.pair || 'UNKNOWN';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!SYMBOLS_FILTER.includes(symbol)) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const price = parseFloat(msg.p || msg.bp || msg.vw || 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const bid = parseFloat(msg.bp || 0) || null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const ask = parseFloat(msg.ap || 0) || null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!price) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const payload = buildPayload(symbol, price, bid, ask, feed.name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!payload) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await axios.post(N8N_WEBHOOK_URL, payload, { timeout: 5000 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(`[${feed.name}] Sent ${symbol} @ ${price}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error(`[${feed.name}] Failed:`, err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ws.on('close', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(`[${feed.name}] Disconnected. Reconnecting in ${reconnectDelay}ms`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setTimeout(() => connectFeed(feed, Math.min(reconnectDelay * 2, 30000)), reconnectDelay);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ws.on('error', (err) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error(`[${feed.name}] Error:`, err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ws.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FEEDS.forEach(feed => connectFeed(feed));